#ifndef _statistics_h_INCLUDED
#define _statistics_h_INCLUDED

// clang-format off

//           NAME,            VERBOSITY (0-3), REFERENCE, PRINT, OTHER
//      length 21,  (Always/!0/verbose/never), (relative/percent/MACRO)
#ifndef NTRACING
#define CADICAL_API_STATISTICS \
  STATISTIC (api_init,                  3, NOTHING, 0, 0) \
  STATISTIC (api_reset,                 3, NOTHING, 0, 0) \
  STATISTIC (api_vars,                  3, NOTHING, 0, 0) \
  STATISTIC (api_declare_var,           3, NOTHING, 0, 0) \
  STATISTIC (api_declare_vars,          3, NOTHING, 0, 0) \
  STATISTIC (api_resize,                3, NOTHING, 0, 0) \
  STATISTIC (api_set,                   3, NOTHING, 0, 0) \
  STATISTIC (api_limit,                 3, NOTHING, 0, 0) \
  STATISTIC (api_configure,             3, NOTHING, 0, 0) \
  STATISTIC (api_add,                   3, NOTHING, 0, 0) \
  STATISTIC (api_constrain,             3, NOTHING, 0, 0) \
  STATISTIC (api_assume,                3, NOTHING, 0, 0) \
  STATISTIC (api_lookahead,             3, NOTHING, 0, 0) \
  STATISTIC (api_lookahead_cubes,       3, NOTHING, 0, 0) \
  STATISTIC (api_reset_assumptions,     3, NOTHING, 0, 0) \
  STATISTIC (api_propagate_assumptions, 3, NOTHING, 0, 0) \
  STATISTIC (api_implied,               3, NOTHING, 0, 0) \
  STATISTIC (api_solve,                 3, NOTHING, 0, 0) \
  STATISTIC (api_simplify,              3, NOTHING, 0, 0) \
  STATISTIC (api_flip,                  3, NOTHING, 0, 0) \
  STATISTIC (api_flippable,             3, NOTHING, 0, 0) \
  STATISTIC (api_failed,                3, NOTHING, 0, 0) \
  STATISTIC (api_constraint_failed,     3, NOTHING, 0, 0) \
  STATISTIC (api_fixed,                 3, NOTHING, 0, 0) \
  STATISTIC (api_phase,                 3, NOTHING, 0, 0) \
  STATISTIC (api_unphase,               3, NOTHING, 0, 0) \
  STATISTIC (api_active,                3, NOTHING, 0, 0) \
  STATISTIC (api_redundant,             3, NOTHING, 0, 0) \
  STATISTIC (api_irredundant,           3, NOTHING, 0, 0) \
  STATISTIC (api_freeze,                3, NOTHING, 0, 0) \
  STATISTIC (api_melt,                  3, NOTHING, 0, 0) \
  STATISTIC (api_frozen,                3, NOTHING, 0, 0) \
  STATISTIC (api_trace_proof,           3, NOTHING, 0, 0) \
  STATISTIC (api_flush_proof_trace,     3, NOTHING, 0, 0) \
  STATISTIC (api_close_proof_trace,     3, NOTHING, 0, 0) \
  STATISTIC (api_conclude,              3, NOTHING, 0, 0) \
  STATISTIC (api_stats,                 3, NOTHING, 0, 0) \
  STATISTIC (api_resources,             3, NOTHING, 0, 0) \
  STATISTIC (api_dump,                  3, NOTHING, 0, 0) \
  STATISTIC (api_observed,              3, NOTHING, 0, 0) \
  STATISTIC (api_is_decision,           3, NOTHING, 0, 0) \
  STATISTIC (api_connect,               3, NOTHING, 0, 0) \
  STATISTIC (api_disconnect,            3, NOTHING, 0, 0) \
  STATISTIC (api_observe,               3, NOTHING, 0, 0) \
  STATISTIC (api_unobserve,             3, NOTHING, 0, 0) \
  STATISTIC (api_reset_observed,        3, NOTHING, 0, 0) \
  STATISTIC (api_force_backtrack,       3, NOTHING, 0, 0) \
  STATISTIC (api_is_witness,            3, NOTHING, 0, 0) \
  STATISTIC (api_force_unassign,        3, NOTHING, 0, 0)

#else
#define CADICAL_API_STATISTICS
#endif

#define CADICAL_STATISTICS \
  CADICAL_API_STATISTICS \
  STATISTIC (backbone_phases,        1, INTERVAL, "",    interval) \
  STATISTIC (backbone_probes,        2, relative, "per", vars) \
  STATISTIC (backbone_rounds,        2, relative, "per", backbone_phases) \
  STATISTIC (backbone_units,         1, relative, "per", backbone_phases) \
  STATISTIC (backtracked,            3, NOTHING, 0, 0) \
  STATISTIC (blocked,                1, percent, "%",   clauses_irredundant) \
  STATISTIC (blocked_candidates,     2, relative, "per", blockings) \
  STATISTIC (blocked_pure_clauses,   2, percent, "%", blocked_pure_literals) \
  STATISTIC (blocked_pure_literals,  2, percent, "%",   vars) \
  STATISTIC (blocked_resolutions,    2, relative, "per", blocked_candidates) \
  STATISTIC (blockings,              1, INTERVAL, "", interval) \
  STATISTIC (clause_improved_glue,   2, relative, "per", clauses_redundant) \
     METRIC (clause_promoted_tier1,  2, relative, "per", clause_improved_glue) \
     METRIC (clause_promoted_tier2,  2, relative, "per", clause_improved_glue) \
  /* cannot be a metric due do stamping! */ \
  STATISTIC (clause_recompute_glue,  2, relative, "per", clauses_redundant) \
  STATISTIC (clauses,                0, NOTHING, 0, 0) \
  STATISTIC (clauses_irredundant,    2, percent, "%",  clauses) \
  STATISTIC (clauses_now_irr,        3, NOTHING, 0, 0) \
  STATISTIC (clauses_now_red,        3, NOTHING, 0, 0) \
  STATISTIC (clauses_now_total,      3, NOTHING, 0, 0) \
  STATISTIC (clauses_redundant,      2, percent, "%",  clauses) \
  STATISTIC (collected,              2, relative, "per", collections) \
  STATISTIC (collections,            1, INTERVAL, "", interval) \
  STATISTIC (compacts,               1, INTERVAL, "", interval) \
  STATISTIC (condition_active,       2, relative, "per", conditionings) \
  STATISTIC (condition_candidates,   2, relative, "per", conditionings) \
  STATISTIC (conditioned,            1, percent, "%",  clauses_irredundant) \
  STATISTIC (conditioned_assign,     2, relative, "per", conditioned) \
  STATISTIC (conditioned_autarky,    2, relative, "per", conditioned) \
  STATISTIC (conditioned_cond,       2, relative, "per", conditioned) \
  STATISTIC (conditioned_initial,    2, relative, "per", conditioned) \
  STATISTIC (conditionings,          1, INTERVAL, "", interval) \
  STATISTIC (condition_pre_assign,   2, relative, "per", conditionings) \
  STATISTIC (condition_pre_autarky,  2, relative, "per", conditionings) \
  STATISTIC (condition_pre_cond,     2, relative, "per", conditionings) \
  STATISTIC (condition_propagated,   2, relative, "per", conditionings) \
  STATISTIC (conflicts,              0, SECONDS, "per",  second) \
  STATISTIC (conflicts_chrono,       2, relative, "per", conflicts) \
  STATISTIC (congruence_ands,        2, relative, "per", congruent) \
  STATISTIC (congruence_dummy_ands,  2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_gates,       2, relative, "per", congruence_rounds) \
     METRIC (congruence_gates_and,   2, percent, "%", congruence_gates) \
     METRIC (congruence_gates_ite,   2, percent, "%", congruence_gates) \
     METRIC (congruence_gates_xor,   2, percent, "%", congruence_gates) \
  STATISTIC (congruence_ites,        2, relative, "per", congruent) \
  STATISTIC (congruence_rounds,      1, INTERVAL, "", interval) \
     METRIC (congruence_rw_ands,     2, relative, "per", congruence_gates) \
     METRIC (congruence_rw_ites,     2, relative, "per", congruence_gates) \
     METRIC (congruence_rw_xors,     2, relative, "per", congruence_gates) \
     METRIC (congruence_simp_ands,   2, relative, "per", congruence_rounds) \
     METRIC (congruence_simp_ites,   2, relative, "per", congruence_rounds) \
     METRIC (congruence_simplified,  2, relative, "per", congruence_rounds) \
     METRIC (congruence_simp_xors,   2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_subsumed,    2, relative, "per", congruence_rounds) \
     METRIC (congruence_trite,       2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_unary,       2, relative, "per", congruence_rounds) \
     METRIC (congruence_unary_and,   2, relative, "per", congruence_rounds) \
     METRIC (congruence_unary_ite,   2, relative, "per", congruence_rounds) \
  STATISTIC (congruence_units,       2, relative, "per", congruent) \
  STATISTIC (congruence_xors,        2, relative, "per", congruent) \
  STATISTIC (congruent,              1, relative, "per", congruence_rounds) \
  STATISTIC (constraints_added,      2, relative, "per", searches) \
  STATISTIC (constraints_analyzed,   2, percent, "%", constraints_sat) \
  STATISTIC (constraints_decided,    2, percent, "%", constraints_added) \
  STATISTIC (constraints_failed,     2, percent, "%", constraints_added) \
  STATISTIC (constraints_flipped,    2, percent, "%", constraints_added) \
  STATISTIC (constraints_lit,        2, relative, "per", constraints_added) \
  STATISTIC (constraints_reset,      2, relative, "per", searches) \
  STATISTIC (constraints_sat,        2, percent, "%", constraints_solved) \
  STATISTIC (constraints_solved,     2, relative, "per", decisions) \
  STATISTIC (constraints_unsat,      2, percent, "%", constraints_solved) \
  STATISTIC (constraints_vars,       2, relative, "per", constraints_added) \
  STATISTIC (cover_asymmetric,       3, percent, "%",  cover_total) \
  STATISTIC (cover_blocked,          3, percent, "%",  cover_total) \
  STATISTIC (coverings,              3, INTERVAL, "", interval) \
  STATISTIC (cover_total,            2, percent, "%",  clauses_irredundant) \
  STATISTIC (decision_random,        2, percent, "%",  decisions) \
  STATISTIC (decision_random_phase,  2, INTERVAL, "", interval) \
  STATISTIC (decisions,              0, SECONDS, "per",  second) \
  STATISTIC (decision_searched,      2, relative, "per", decisions) \
  STATISTIC (decompositions,         1, INTERVAL, "", interval) \
  STATISTIC (deduplicated,           1, percent, "%",  subsumed) \
  STATISTIC (deduplicate_init,       2, percent, "%",  subsumed) \
  STATISTIC (deduplicate_rounds,     2, relative, "per", searches) \
  STATISTIC (deduplicate_unary,      2, relative, "per", deduplications) \
  STATISTIC (deduplications,         1, INTERVAL, "", interval) \
  STATISTIC (eager_subsumed,         1, percent, "%",  subsumed) \
  STATISTIC (eager_subsumptions,     2, relative, "per", eager_subsumed) \
  STATISTIC (eliminate_and,          2, percent, "%", eliminate_gates) \
  STATISTIC (eliminate_complete,     2, percent, "%", eliminations) \
  STATISTIC (eliminated,             1, percent, "%",  vars) \
  STATISTIC (eliminated_and,         2, percent, "%",  eliminated) \
  STATISTIC (eliminated_defs,        2, percent, "%",  eliminated) \
  STATISTIC (eliminate_def_check,    2, relative, "per", eliminated_defs) \
  STATISTIC (eliminate_def_success,  2, percent, "%", eliminate_def_check) \
  STATISTIC (eliminate_def_ticks,    2, percent, "%",  ticks) \
  STATISTIC (eliminate_def_unit,     2, relative, "per", eliminate_def_check) \
  STATISTIC (eliminated_equivalent,  2, percent, "%",  eliminated) \
  STATISTIC (eliminated_ite,         2, percent, "%",  eliminated) \
  STATISTIC (eliminated_xor,         2, percent, "%",  eliminated) \
  STATISTIC (eliminate_equivalence,  2, relative, "per", eliminate_gates) \
  STATISTIC (eliminate_fast_phases,  2, relative, "per", eliminate_fast_rounds) \
  STATISTIC (eliminate_fast_rounds,  2, relative, "per", searches) \
  STATISTIC (eliminate_gates,        2, percent, "%",  eliminate_tried) \
  STATISTIC (eliminate_ite,          2, percent, "%",  eliminate_gates) \
  STATISTIC (eliminate_otf_str,      2, percent, "%",  eliminate_tried) \
  STATISTIC (eliminate_otf_sub,      2, percent, "%",  eliminate_tried) \
  STATISTIC (eliminate_phases,       2, relative, "per", eliminations) \
  STATISTIC (eliminate_resolved,     2, relative, "per", eliminated) \
  STATISTIC (eliminate_strength_bw,  2, percent, "%", eliminate_tried) \
  STATISTIC (eliminate_substituted,  2, percent, "%", eliminate_tried) \
  STATISTIC (eliminate_subsumed_bw,  2, percent, "%", eliminate_tried) \
  STATISTIC (eliminate_tried,        2, relative, "per", eliminations) \
  STATISTIC (eliminate_tried_res,    2, relative, "per", eliminate_tried) \
  STATISTIC (eliminate_xor,          2, percent, "%", eliminate_gates) \
  STATISTIC (eliminations,           1, INTERVAL, "", interval) \
  STATISTIC (extended,               1, relative, "per", weakened) \
  STATISTIC (extensions,             1, relative, "per", searches) \
  STATISTIC (factor_added_clauses,   2, relative, "per", factored) \
  STATISTIC (factor_added_literals,  2, relative, "per", factored) \
  STATISTIC (factored,               1, percent, "%", vars) \
  STATISTIC (factored_and,           2, percent, "%", factored) \
  STATISTIC (factored_eliminated,    2, percent, "%", factored) \
  STATISTIC (factored_ite,           2, percent, "%", factored) \
  STATISTIC (factored_xor,           2, percent, "%", factored) \
  STATISTIC (factorings,             1, INTERVAL, "", interval) \
  STATISTIC (factor_removed_irr,     2, relative, "per", factored) \
  STATISTIC (factor_removed_lits,    2, relative, "per", factored) \
  STATISTIC (factor_removed_red,     2, relative, "per", factored) \
  STATISTIC (failed_literals,        1, percent, "%", vars) \
  STATISTIC (flush_hyper,            2, percent, "%", flush_learned) \
  STATISTIC (flushings,              1, INTERVAL, "", interval) \
  STATISTIC (flush_learned,          1, percent, "%", clauses_redundant) \
  STATISTIC (garbage_bytes,          3, NOTHING, 0, 0) \
  STATISTIC (garbage_clauses,        3, NOTHING, 0, 0) \
  STATISTIC (garbage_literals,       3, NOTHING, 0, 0) \
  STATISTIC (hbr_redundant,          2, percent, "%", hbrs) \
  STATISTIC (hbrs,                   1, relative, "per", probed) \
  STATISTIC (hbr_sizes,              2, relative, "per", hbrs) \
  STATISTIC (hbr_subsuming,          2, relative, "per", hbrs) \
  STATISTIC (ilb_reuse_assumptions,  2, relative, "per", ilb_success) \
  STATISTIC (ilb_reuse_levels,       2, relative, "per", ilb_success) \
  STATISTIC (ilb_reuse_literals,     2, relative, "per", ilb_success) \
  STATISTIC (ilb_success,            1, relative, "per", ilb_triggers) \
  STATISTIC (ilb_triggers,           2, relative, "per", searches) \
  STATISTIC (incremental_decay,      1, relative, "per", searches) \
  STATISTIC (inprobingphases,        1, INTERVAL, "", interval) \
  STATISTIC (inprobingsuccess,       1, percent, "%", inprobingphases) \
  STATISTIC (instantiated,           1, relative, "per", instantiate_tried) \
  STATISTIC (instantiate_tried,      2, relative, "per", instantiations) \
  STATISTIC (instantiations,         1, INTERVAL, "", interval) \
  STATISTIC (irredundant_literals,   3, NOTHING, 0, 0) \
  STATISTIC (learned_binaries,       2, percent, "%", learned_clauses) \
  STATISTIC (learned_clauses,        2, percent, "%", clauses) \
  STATISTIC (learned_literals,       2, relative, "per", learned_clauses) \
  STATISTIC (learned_units,          2, percent, "%", learned_clauses) \
  STATISTIC (lucky,                  1, percent, "%", lucky_tried) \
  STATISTIC (lucky_backward_one,     2, percent, "%", lucky_tried) \
  STATISTIC (lucky_backward_zero,    2, percent, "%", lucky_tried) \
  STATISTIC (lucky_constant_one,     2, percent, "%", lucky_tried) \
  STATISTIC (lucky_constant_zero,    2, percent, "%", lucky_tried) \
  STATISTIC (lucky_forward_one,      2, percent, "%", lucky_tried) \
  STATISTIC (lucky_forward_zero,     2, percent, "%", lucky_tried) \
  STATISTIC (lucky_random,           2, percent, "%", lucky_tried) \
  STATISTIC (lucky_tried,            2, relative, "per", searches) \
  STATISTIC (lucky_units,            2, percent, "%", lucky_tried) \
  STATISTIC (mark_block,             3, NOTHING, 0, 0) \
  STATISTIC (mark_elim,              3, NOTHING, 0, 0) \
  STATISTIC (mark_factor,            3, NOTHING, 0, 0) \
  STATISTIC (mark_subsume,           3, NOTHING, 0, 0) \
  STATISTIC (mark_ternary,           3, NOTHING, 0, 0) \
  STATISTIC (minimized,              1, relative, "per", learned_literals) \
  STATISTIC (otfs_strengthened,      1, percent, "%", conflicts) \
  STATISTIC (otfs_subsumed,          1, percent, "%", conflicts) \
  STATISTIC (preprocessings,         2, relative, "per", searches) \
  STATISTIC (probed,                 1, percent, "%", vars) \
  STATISTIC (probe_failed_literals,  1, relative, "per", probed) \
  STATISTIC (probingrounds,          2, INTERVAL, "", interval) \
  STATISTIC (propagations,           0, MSECONDS, "M", per second) \
  STATISTIC (propagations_backbone,  2, percent, "%", propagations) \
  STATISTIC (propagations_cover,     2, percent, "%", propagations) \
  STATISTIC (propagations_inst,      2, percent, "%", propagations) \
  STATISTIC (propagations_probe,     2, percent, "%", propagations) \
  STATISTIC (propagations_search,    2, percent, "%", propagations) \
  STATISTIC (propagations_transred,  2, percent, "%", propagations) \
  STATISTIC (propagations_vivify,    2, percent, "%", propagations) \
  STATISTIC (recomputed_tiers,       1, INTERVAL, "", interval) \
  STATISTIC (reduced,                1, percent, "%", learned_clauses) \
  STATISTIC (reductions,             1, INTERVAL, "", interval) \
  STATISTIC (rephased,               1, INTERVAL, "", interval) \
  STATISTIC (rephased_best,          2, percent, "%", rephased) \
  STATISTIC (rephased_flipped,       2, percent, "%", rephased) \
  STATISTIC (rephased_inverted,      2, percent, "%", rephased) \
  STATISTIC (rephased_original,      2, percent, "%", rephased) \
  STATISTIC (rephased_random,        2, percent, "%", rephased) \
  STATISTIC (rephased_walk,          2, percent, "%", rephased) \
  STATISTIC (restart,                1, INTERVAL, "", interval) \
  STATISTIC (restart_levels,         2, relative, "per", restart) \
  STATISTIC (restart_stable,         2, percent, "%", restart) \
  STATISTIC (restorations,           1, relative, "per", searches) \
  STATISTIC (restored_clauses,       1, relative, "per", restorations) \
  STATISTIC (restored_literals,      2, relative, "per", restored_clauses) \
  STATISTIC (reused,                 1, relative, "per", restart) \
  STATISTIC (reused_levels,          2, relative, "per", reused) \
  STATISTIC (reused_stable,          2, relative, "per", reused) \
  STATISTIC (scores_rescored,        2, percent, "%", conflicts) \
  STATISTIC (scores_shuffled,        2, relative, "per", rephased) \
  STATISTIC (searches,               0, NOTHING, 0, 0) \
  STATISTIC (sections,               3, NOTHING, 0, 0) \
  STATISTIC (shrunken,               1, percent, "%", learned_literals) \
  STATISTIC (shrunken_minimize,      1, percent, "%", learned_literals) \
  STATISTIC (stable_conflicts,       2, percent, "%", conflicts) \
  STATISTIC (stable_phases_current,  2, INTERVAL, "", interval) \
  STATISTIC (stable_phases_total,    1, INTERVAL, "", interval) \
  STATISTIC (strengthened,           1, percent, "%", clauses) \
  STATISTIC (subsume_checks,         2, relative, "per", subsume_tried) \
  STATISTIC (subsume_checks_binary,  2, percent, "%", subsume_checks) \
  STATISTIC (subsumed,               1, percent, "%", clauses) \
  STATISTIC (subsumed_irredundant,   2, percent, "%", subsumed) \
  STATISTIC (subsumed_redundant,     2, percent, "%", subsumed) \
  STATISTIC (subsume_phases,         2, relative, "per", subsume_rounds) \
  STATISTIC (subsume_rounds,         2, INTERVAL, "", interval) \
  STATISTIC (subsume_tried,          2, relative, "per", subsumed) \
  STATISTIC (sweepings,              1, INTERVAL, "", interval) \
  STATISTIC (sweep_bb_fixed,         2, relative, "per", sweep_variables) \
  STATISTIC (sweep_bb_flip,          2, relative, "per", sweep_variables) \
  STATISTIC (sweep_bb_flipped,       2, percent, "%", sweep_bb_flip) \
  STATISTIC (sweep_bb_solved,        2, percent, "%", sweep_solved) \
  STATISTIC (sweep_bb_solved_sat,    2, percent, "%", sweep_bb_solved) \
  STATISTIC (sweep_bb_solved_to,     2, percent, "%", sweep_bb_solved) \
  STATISTIC (sweep_bb_solved_unsat,  2, percent, "%", sweep_bb_solved) \
  STATISTIC (sweep_clauses,          2, relative, "per", sweep_variables) \
  STATISTIC (sweep_completed,        2, relative, "per", sweepings) \
  STATISTIC (sweep_depth,            2, relative, "per", sweep_variables) \
  STATISTIC (sweep_environment,      2, relative, "per", sweep_variables) \
  STATISTIC (sweep_eq,               1, relative, "per", sweep_variables) \
  STATISTIC (sweep_eq_flip,          2, relative, "per", sweep_variables) \
  STATISTIC (sweep_eq_flipped,       2, percent, "%", sweep_eq_flip) \
  STATISTIC (sweep_eq_solved,        2, percent, "%", sweep_solved) \
  STATISTIC (sweep_eq_solved_sat,    2, percent, "%", sweep_eq_solved) \
  STATISTIC (sweep_eq_solved_to,     2, percent, "%", sweep_eq_solved) \
  STATISTIC (sweep_eq_solved_unsat,  2, percent, "%", sweep_eq_solved) \
  STATISTIC (sweep_solved,           2, relative, "per", sweep_variables) \
  STATISTIC (sweep_solved_sat,       2, percent, "%", sweep_solved) \
  STATISTIC (sweep_solved_to,        2, percent, "%", sweep_solved) \
  STATISTIC (sweep_solved_unsat,     2, percent, "%", sweep_solved) \
  STATISTIC (sweep_units,            1, percent, "%", vars) \
  STATISTIC (sweep_variables,        2, relative, "per", vars) \
  STATISTIC (ternary,                1, INTERVAL, "", interval) \
  STATISTIC (ternary_htrs,           1, percent, "%", ternary_resolutions) \
  STATISTIC (ternary_htrs_binary,    2, percent, "%", ternary_htrs) \
  STATISTIC (ternary_htrs_ternary,   2, percent, "%", ternary_htrs) \
  STATISTIC (ternary_resolutions,    2, relative, "per", ternary) \
  STATISTIC (ticks,                  0, MSECONDS, "M", per second) \
  STATISTIC (ticks_backbone,         2, percent, "%", ticks) \
  STATISTIC (ticks_elim,             2, percent, "%", ticks) \
  STATISTIC (ticks_fastelim,         2, percent, "%", ticks) \
  STATISTIC (ticks_factor,           2, percent, "%", ticks) \
  STATISTIC (ticks_probe,            2, percent, "%", ticks) \
  STATISTIC (ticks_search_stable,    2, percent, "%", ticks) \
  STATISTIC (ticks_search_unstable,  2, percent, "%", ticks) \
  STATISTIC (ticks_sweep,            2, percent, "%", ticks) \
  STATISTIC (ticks_ternary,          2, percent, "%", ticks) \
  STATISTIC (ticks_vivify,           2, percent, "%", ticks) \
  STATISTIC (ticks_walk,             2, percent, "%", ticks) \
     METRIC (ticks_walk_break,       2, percent, "%", ticks_walk) \
     METRIC (ticks_walk_flip,        2, percent, "%", ticks_walk) \
     METRIC (ticks_walk_flip_broke,  2, percent, "%", ticks_walk) \
     METRIC (ticks_walk_flip_wl,     2, percent, "%", ticks_walk) \
     METRIC (ticks_walk_pick,        2, percent, "%", ticks_walk) \
  STATISTIC (transitive_clauses,     1, percent, "%", subsumed) \
  STATISTIC (transitive_rounds,      1, INTERVAL, "", interval) \
  STATISTIC (transitive_units,       2, percent, "%", failed_literals) \
  STATISTIC (up_cb,                  2, relative, "per", searches) \
  STATISTIC (up_cb_add,              2, percent, "%", up_cb) \
  STATISTIC (up_cb_check_model,      2, percent, "%", up_cb) \
  STATISTIC (up_cb_decide,           2, percent, "%", up_cb) \
  STATISTIC (up_cb_decided,          2, percent, "%", up_cb_decide) \
  STATISTIC (up_cb_decide_force_bt,  2, percent, "%", up_cb_decide) \
  STATISTIC (up_cb_prop,             2, percent, "%", up_cb) \
     METRIC (up_cb_prop_assign,      2, percent, "%", up_cb_prop) \
     METRIC (up_cb_prop_clash,       2, percent, "%", up_cb_prop) \
     METRIC (up_cb_prop_explain,     2, percent, "%", up_cb_prop) \
  STATISTIC (up_learn,               2, percent, "%", clauses) \
     METRIC (up_learn_conflict,      2, percent, "%", up_learn) \
     METRIC (up_learn_elevating,     2, percent, "%", up_learn) \
     METRIC (up_learn_empty,         2, percent, "%", up_learn) \
     METRIC (up_learn_lazy_elevate,  2, percent, "%", up_learn) \
     METRIC (up_learn_out_of_order,  2, percent, "%", up_learn) \
     METRIC (up_learn_propagating,   2, percent, "%", up_learn) \
     METRIC (up_learn_satisfied,     2, percent, "%", up_learn) \
     METRIC (up_learn_unit,          2, percent, "%", up_learn) \
  STATISTIC (variables_extension,    2, percent, "%", vars) \
  STATISTIC (variables_original,     1, percent, "%", vars) \
  STATISTIC (vars,                   0, NOTHING, 0, 0) \
  STATISTIC (vars_active,            2, percent, "%", vars) \
  STATISTIC (vars_all_elim,          2, percent, "%", vars) \
  STATISTIC (vars_all_elim_fast,     2, percent, "%", vars) \
  STATISTIC (vars_all_fixed,         2, percent, "%", vars) \
  STATISTIC (vars_all_pure,          2, percent, "%", vars) \
  STATISTIC (vars_all_substituted,   2, percent, "%", vars) \
  STATISTIC (vars_bumped,            2, percent, "%", vars) \
  STATISTIC (vars_declared,          2, percent, "%", vars) \
  STATISTIC (vars_inactive,          2, percent, "%", vars) \
  STATISTIC (vars_now_eliminated,    3, NOTHING, 0, 0) \
  STATISTIC (vars_now_fixed,         3, NOTHING, 0, 0) \
  STATISTIC (vars_now_pure,          3, NOTHING, 0, 0) \
  STATISTIC (vars_now_substituted,   3, NOTHING, 0, 0) \
  STATISTIC (vars_reactivated,       2, percent, "%", vars) \
  STATISTIC (vars_unused,            2, percent, "%", vars) \
  STATISTIC (vivifications,          1, INTERVAL, "", interval) \
  STATISTIC (vivified,               1, percent, "%", clauses) \
     METRIC (vivified_irr,           2, percent, "%", vivified) \
     METRIC (vivified_tier1,         2, percent, "%", vivified) \
     METRIC (vivified_tier2,         2, percent, "%", vivified) \
     METRIC (vivified_tier3,         2, percent, "%", vivified) \
  STATISTIC (vivify_checks,          2, percent, "%", vivify_scheduled) \
     METRIC (vivify_decisions,       2, relative, "per", vivify_checks) \
     METRIC (vivify_demote,          2, percent, "%", vivify_strength) \
     METRIC (vivify_flushed,         2, percent, "%", vivify_subsumed) \
     METRIC (vivify_implied,         2, percent, "%", vivify_checks) \
     METRIC (vivify_instantiated,    2, percent, "%", vivify_checks) \
     METRIC (vivify_reused,          2, percent, "%", vivify_decisions) \
  STATISTIC (vivify_scheduled,       2, relative, "per", vivifications) \
     METRIC (vivify_strength,        2, percent, "%", strengthened) \
     METRIC (vivify_strength_irr,    2, percent, "%", vivify_strength) \
     METRIC (vivify_strength_tier1,  2, percent, "%", vivify_strength) \
     METRIC (vivify_strength_tier2,  2, percent, "%", vivify_strength) \
     METRIC (vivify_strength_tier3,  2, percent, "%", vivify_strength) \
     METRIC (vivify_subsumed,        2, percent, "%", subsumed) \
     METRIC (vivify_subsumed_irr,    2, percent, "%", vivify_subsumed) \
     METRIC (vivify_subsumed_red,    2, percent, "%", vivify_subsumed) \
     METRIC (vivify_units,           2, percent, "%", vivify_checks) \
  STATISTIC (walk,                   1, INTERVAL, "", interval) \
     METRIC (walk_broken,            2, relative, "per", walk_flips) \
  STATISTIC (walk_flips,             2, RELPROFW,"M", per second walk) \
     METRIC (walk_flips_reducing,    2, percent, "%", walk_flips) \
     METRIC (walk_flips_sideways,    2, percent, "%", walk_flips) \
     METRIC (walk_flips_transfer,    2, percent, "%", walk_flips) \
  STATISTIC (walk_improved,          2, relative, "per", walk) \
  STATISTIC (walk_warmup,            2, percent, "%", walk) \
     METRIC (walk_warmup_conflicts,  2, relative, "per", walk_warmup) \
     METRIC (walk_warmup_decision,   2, relative, "per", walk_warmup) \
     METRIC (walk_warmup_dummy,      2, relative, "per", walk_warmup) \
     METRIC (walk_warmup_propagate,  2, relative, "per", walk_warmup) \
  STATISTIC (weakened,               1, percent, "%", clauses) \
  STATISTIC (weakened_lengths,       2, relative, "per", weakened)

// clang-format on

#endif
